### ISSUE TITLE
Doesn't install in Windows

### ISSUE THREAD

**Issue by plasmaphase** [SkypLabs/python-hdlc-controller#8] opened 2019-08-23 18:21 UTC
When trying to install in windows I get the following error:

`ValueError: path '/home/travis/build/SkypLabs/python4yahdlc/lib/fcs16.c' cannot be absolute`

**Comment by SkypLabs** [comment] 2019-08-25 13:04
Hello @plasmaphase,

Thank you for reporting this issue.

It is actually a known problem caused by the `python4yahdlc` dependency that I develop as well: https://github.com/SkypLabs/python4yahdlc/issues/3.

Consequently, I will close this issue.

**Closed by SkypLabs** 2019-08-25 13:04 UTC
